In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Replace the path with the correct path for your data.
y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

# Note the warning about dtypes.

C:\dev_software\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
y2015.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68009401,72868139.0,16000.0,16000.0,16000.0,60 months,14.85%,379.39,C,C5,...,0.0,2.0,78.9,0.0,0.0,2.0,298100.0,31329.0,281300.0,13400.0
1,68354783,73244544.0,9600.0,9600.0,9600.0,36 months,7.49%,298.58,A,A4,...,0.0,2.0,100.0,66.7,0.0,0.0,88635.0,55387.0,12500.0,75635.0
2,68466916,73356753.0,25000.0,25000.0,25000.0,36 months,7.49%,777.55,A,A4,...,0.0,0.0,100.0,20.0,0.0,0.0,373572.0,68056.0,38400.0,82117.0
3,68466961,73356799.0,28000.0,28000.0,28000.0,36 months,6.49%,858.05,A,A2,...,0.0,0.0,91.7,22.2,0.0,0.0,304003.0,74920.0,41500.0,42503.0
4,68495092,73384866.0,8650.0,8650.0,8650.0,36 months,19.89%,320.99,E,E3,...,0.0,12.0,100.0,50.0,1.0,0.0,38998.0,18926.0,2750.0,18248.0

In [4]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421097
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3

In [5]:
# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [6]:
y2015.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
421092,36271333.0,38982739.0,13000.0,13000.0,13000.0,60 months,15.99,316.07,D,5 years,...,0.0,3.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,36490806.0,39222577.0,12000.0,12000.0,12000.0,60 months,19.99,317.86,E,1 year,...,1.0,2.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421094,36271262.0,38982659.0,20000.0,20000.0,20000.0,36 months,11.99,664.20,B,10+ years,...,0.0,1.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0
421095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
y2015 = y2015[:-2]

In [8]:
#pd.get_dummies(y2015)

In [9]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

C:\dev_software\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

array([0.977963  , 0.98069388, 0.98135879, 0.9816675 , 0.97038708,
       0.9768701 , 0.93609442, 0.98076421, 0.98012207, 0.98043034])

## More Clean Up

In [10]:
y2015.drop(['id','member_id','issue_d'],1, inplace=True)

In [13]:
#corr_sort = pd.get_dummies(y2015).corr().unstack().sort_values(kind='quicksort',ascending=False)
#print(corr_sort)

In [12]:
#corr_sort = np.array(corr_sort)
#corr_sort[np.logical_and(corr_sort<1,corr_sort>0.75)]

In [25]:
rows, cols = y2015.shape
flds = list(y2015.columns)

# Indexing with numbers on a numpy matrix will probably be faster
corr = y2015.corr().unstack().values

for i in range(cols):
    for j in range(i+1, cols):
        if corr[i] > 0.75 and corr[i] < 1:
            print(flds[i], ' ', flds[j], ' ', corr[i])

funded_amnt_inv   term   0.9999944873453467
funded_amnt_inv   int_rate   0.9999944873453467
funded_amnt_inv   installment   0.9999944873453467
funded_amnt_inv   grade   0.9999944873453467
funded_amnt_inv   emp_length   0.9999944873453467
funded_amnt_inv   home_ownership   0.9999944873453467
funded_amnt_inv   annual_inc   0.9999944873453467
funded_amnt_inv   verification_status   0.9999944873453467
funded_amnt_inv   loan_status   0.9999944873453467
funded_amnt_inv   pymnt_plan   0.9999944873453467
funded_amnt_inv   purpose   0.9999944873453467
funded_amnt_inv   title   0.9999944873453467
funded_amnt_inv   dti   0.9999944873453467
funded_amnt_inv   delinq_2yrs   0.9999944873453467
funded_amnt_inv   inq_last_6mths   0.9999944873453467
funded_amnt_inv   mths_since_last_delinq   0.9999944873453467
funded_amnt_inv   mths_since_last_record   0.9999944873453467
funded_amnt_inv   open_acc   0.9999944873453467
funded_amnt_inv   pub_rec   0.9999944873453467
funded_amnt_inv   revol_bal   0.9999944873453467
funded_amnt_inv   total_acc   0.9999944873453467
funded_amnt_inv   initial_list_status   0.9999944873453467
funded_amnt_inv   out_prncp   0.9999944873453467
funded_amnt_inv   out_prncp_inv   0.9999944873453467
funded_amnt_inv   total_pymnt   0.9999944873453467
funded_amnt_inv   total_pymnt_inv   0.9999944873453467
funded_amnt_inv   total_rec_prncp   0.9999944873453467
funded_amnt_inv   total_rec_int   0.9999944873453467
funded_amnt_inv   total_rec_late_fee   0.9999944873453467
funded_amnt_inv   recoveries   0.9999944873453467
funded_amnt_inv   collection_recovery_fee   0.9999944873453467
funded_amnt_inv   last_pymnt_d   0.9999944873453467
funded_amnt_inv   last_pymnt_amnt   0.9999944873453467
funded_amnt_inv   next_pymnt_d   0.9999944873453467
funded_amnt_inv   last_credit_pull_d   0.9999944873453467
funded_amnt_inv   collections_12_mths_ex_med   0.9999944873453467
funded_amnt_inv   mths_since_last_major_derog   0.9999944873453467
funded_amnt_inv   policy_code   0.9999944873453467
funded_amnt_inv   application_type   0.9999944873453467
funded_amnt_inv   annual_inc_joint   0.9999944873453467
funded_amnt_inv   dti_joint   0.9999944873453467
funded_amnt_inv   verification_status_joint   0.9999944873453467
funded_amnt_inv   acc_now_delinq   0.9999944873453467
funded_amnt_inv   tot_coll_amt   0.9999944873453467
funded_amnt_inv   tot_cur_bal   0.9999944873453467
funded_amnt_inv   open_acc_6m   0.9999944873453467
funded_amnt_inv   open_il_6m   0.9999944873453467
funded_amnt_inv   open_il_12m   0.9999944873453467
funded_amnt_inv   open_il_24m   0.9999944873453467
funded_amnt_inv   mths_since_rcnt_il   0.9999944873453467
funded_amnt_inv   total_bal_il   0.9999944873453467
funded_amnt_inv   il_util   0.9999944873453467
funded_amnt_inv   open_rv_12m   0.9999944873453467
funded_amnt_inv   open_rv_24m   0.9999944873453467
funded_amnt_inv   max_bal_bc   0.9999944873453467
funded_amnt_inv   all_util   0.9999944873453467
funded_amnt_inv   total_rev_hi_lim   0.9999944873453467
funded_amnt_inv   inq_fi   0.9999944873453467
funded_amnt_inv   total_cu_tl   0.9999944873453467
funded_amnt_inv   inq_last_12m   0.9999944873453467
funded_amnt_inv   acc_open_past_24mths   0.9999944873453467
funded_amnt_inv   avg_cur_bal   0.9999944873453467
funded_amnt_inv   bc_open_to_buy   0.9999944873453467
funded_amnt_inv   bc_util   0.9999944873453467
funded_amnt_inv   chargeoff_within_12_mths   0.9999944873453467
funded_amnt_inv   delinq_amnt   0.9999944873453467
funded_amnt_inv   mo_sin_old_il_acct   0.9999944873453467
funded_amnt_inv   mo_sin_old_rev_tl_op   0.9999944873453467
funded_amnt_inv   mo_sin_rcnt_rev_tl_op   0.9999944873453467
funded_amnt_inv   mo_sin_rcnt_tl   0.9999944873453467
funded_amnt_inv   mort_acc   0.9999944873453467
funded_amnt_inv   mths_since_recent_bc   0.9999944873453467
funded_amnt_inv   mths_since_recent_bc_dlq   0.9999944873453467
funded_amnt_inv   mths_since_recent_inq   0.9999944873453467
funded_amnt_inv   mths_since_recent_revol_delinq   0.9999944873453467
funded_amnt_inv   num_accts_ever_120_pd   0.9999944873453467
funded_amnt_inv   num_actv_bc_tl   0.9999944873453467
funded_amnt_inv   num_actv_rev_tl   0.9999944873453467
funded_amnt_inv   num_bc_sats   0.9999944873453467
funded_amnt_inv   num_bc_tl   0.9999944873453467
funded_amnt_inv   num_il_tl   0.9999944873453467
funded_amnt_inv   num_op_rev_tl   0.9999944873453467
funded_amnt_inv   num_rev_accts   0.9999944873453467
funded_amnt_inv   num_rev_tl_bal_gt_0   0.9999944873453467
funded_amnt_inv   num_sats   0.9999944873453467
funded_amnt_inv   num_tl_120dpd_2m   0.9999944873453467
funded_amnt_inv   num_tl_30dpd   0.9999944873453467
funded_amnt_inv   num_tl_90g_dpd_24m   0.9999944873453467
funded_amnt_inv   num_tl_op_past_12m   0.9999944873453467
funded_amnt_inv   pct_tl_nvr_dlq   0.9999944873453467
funded_amnt_inv   percent_bc_gt_75   0.9999944873453467
funded_amnt_inv   pub_rec_bankruptcies   0.9999944873453467
funded_amnt_inv   tax_liens   0.9999944873453467
funded_amnt_inv   tot_hi_cred_lim   0.9999944873453467
funded_amnt_inv   total_bal_ex_mort   0.9999944873453467
funded_amnt_inv   total_bc_limit   0.9999944873453467
funded_amnt_inv   total_il_high_credit_limit   0.9999944873453467
int_rate   installment   0.9412046763263368
int_rate   grade   0.9412046763263368
int_rate   emp_length   0.9412046763263368
int_rate   home_ownership   0.9412046763263368
int_rate   annual_inc   0.9412046763263368
int_rate   verification_status   0.9412046763263368
int_rate   loan_status   0.9412046763263368
int_rate   pymnt_plan   0.9412046763263368
int_rate   purpose   0.9412046763263368
int_rate   title   0.9412046763263368
int_rate   dti   0.9412046763263368
int_rate   delinq_2yrs   0.9412046763263368
int_rate   inq_last_6mths   0.9412046763263368
int_rate   mths_since_last_delinq   0.9412046763263368
int_rate   mths_since_last_record   0.9412046763263368
int_rate   open_acc   0.9412046763263368
int_rate   pub_rec   0.9412046763263368
int_rate   revol_bal   0.9412046763263368
int_rate   total_acc   0.9412046763263368
int_rate   initial_list_status   0.9412046763263368
int_rate   out_prncp   0.9412046763263368
int_rate   out_prncp_inv   0.9412046763263368
int_rate   total_pymnt   0.9412046763263368
int_rate   total_pymnt_inv   0.9412046763263368
int_rate   total_rec_prncp   0.9412046763263368
int_rate   total_rec_int   0.9412046763263368
int_rate   total_rec_late_fee   0.9412046763263368
int_rate   recoveries   0.9412046763263368
int_rate   collection_recovery_fee   0.9412046763263368
int_rate   last_pymnt_d   0.9412046763263368
int_rate   last_pymnt_amnt   0.9412046763263368
int_rate   next_pymnt_d   0.9412046763263368
int_rate   last_credit_pull_d   0.9412046763263368
int_rate   collections_12_mths_ex_med   0.9412046763263368
int_rate   mths_since_last_major_derog   0.9412046763263368
int_rate   policy_code   0.9412046763263368
int_rate   application_type   0.9412046763263368
int_rate   annual_inc_joint   0.9412046763263368
int_rate   dti_joint   0.9412046763263368
int_rate   verification_status_joint   0.9412046763263368
int_rate   acc_now_delinq   0.9412046763263368
int_rate   tot_coll_amt   0.9412046763263368
int_rate   tot_cur_bal   0.9412046763263368
int_rate   open_acc_6m   0.9412046763263368
int_rate   open_il_6m   0.9412046763263368
int_rate   open_il_12m   0.9412046763263368
int_rate   open_il_24m   0.9412046763263368
int_rate   mths_since_rcnt_il   0.9412046763263368
int_rate   total_bal_il   0.9412046763263368
int_rate   il_util   0.9412046763263368
int_rate   open_rv_12m   0.9412046763263368
int_rate   open_rv_24m   0.9412046763263368
int_rate   max_bal_bc   0.9412046763263368
int_rate   all_util   0.9412046763263368
int_rate   total_rev_hi_lim   0.9412046763263368
int_rate   inq_fi   0.9412046763263368
int_rate   total_cu_tl   0.9412046763263368
int_rate   inq_last_12m   0.9412046763263368
int_rate   acc_open_past_24mths   0.9412046763263368
int_rate   avg_cur_bal   0.9412046763263368
int_rate   bc_open_to_buy   0.9412046763263368
int_rate   bc_util   0.9412046763263368
int_rate   chargeoff_within_12_mths   0.9412046763263368
int_rate   delinq_amnt   0.9412046763263368
int_rate   mo_sin_old_il_acct   0.9412046763263368
int_rate   mo_sin_old_rev_tl_op   0.9412046763263368
int_rate   mo_sin_rcnt_rev_tl_op   0.9412046763263368
int_rate   mo_sin_rcnt_tl   0.9412046763263368
int_rate   mort_acc   0.9412046763263368
int_rate   mths_since_recent_bc   0.9412046763263368
int_rate   mths_since_recent_bc_dlq   0.9412046763263368
int_rate   mths_since_recent_inq   0.9412046763263368
int_rate   mths_since_recent_revol_delinq   0.9412046763263368
int_rate   num_accts_ever_120_pd   0.9412046763263368
int_rate   num_actv_bc_tl   0.9412046763263368
int_rate   num_actv_rev_tl   0.9412046763263368
int_rate   num_bc_sats   0.9412046763263368
int_rate   num_bc_tl   0.9412046763263368
int_rate   num_il_tl   0.9412046763263368
int_rate   num_op_rev_tl   0.9412046763263368
int_rate   num_rev_accts   0.9412046763263368
int_rate   num_rev_tl_bal_gt_0   0.9412046763263368
int_rate   num_sats   0.9412046763263368
int_rate   num_tl_120dpd_2m   0.9412046763263368
int_rate   num_tl_30dpd   0.9412046763263368
int_rate   num_tl_90g_dpd_24m   0.9412046763263368
int_rate   num_tl_op_past_12m   0.9412046763263368
int_rate   pct_tl_nvr_dlq   0.9412046763263368
int_rate   percent_bc_gt_75   0.9412046763263368
int_rate   pub_rec_bankruptcies   0.9412046763263368
int_rate   tax_liens   0.9412046763263368
int_rate   tot_hi_cred_lim   0.9412046763263368
int_rate   total_bal_ex_mort   0.9412046763263368
int_rate   total_bc_limit   0.9412046763263368
int_rate   total_il_high_credit_limit   0.9412046763263368
num_sats   num_tl_120dpd_2m   0.9999944873453467
num_sats   num_tl_30dpd   0.9999944873453467
num_sats   num_tl_90g_dpd_24m   0.9999944873453467
num_sats   num_tl_op_past_12m   0.9999944873453467
num_sats   pct_tl_nvr_dlq   0.9999944873453467
num_sats   percent_bc_gt_75   0.9999944873453467
num_sats   pub_rec_bankruptcies   0.9999944873453467
num_sats   tax_liens   0.9999944873453467
num_sats   tot_hi_cred_lim   0.9999944873453467
num_sats   total_bal_ex_mort   0.9999944873453467
num_sats   total_bc_limit   0.9999944873453467
num_sats   total_il_high_credit_limit   0.9999944873453467
num_tl_30dpd   num_tl_90g_dpd_24m   0.9412046763263368
num_tl_30dpd   num_tl_op_past_12m   0.9412046763263368
num_tl_30dpd   pct_tl_nvr_dlq   0.9412046763263368
num_tl_30dpd   percent_bc_gt_75   0.9412046763263368
num_tl_30dpd   pub_rec_bankruptcies   0.9412046763263368
num_tl_30dpd   tax_liens   0.9412046763263368
num_tl_30dpd   tot_hi_cred_lim   0.9412046763263368
num_tl_30dpd   total_bal_ex_mort   0.9412046763263368
num_tl_30dpd   total_bc_limit   0.9412046763263368
num_tl_30dpd   total_il_high_credit_limit   0.9412046763263368